
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>
#include "Props.h"

namespace facebook {
namespace react {

RNCCheckboxProps::RNCCheckboxProps(
    const PropsParserContext &context,
    const RNCCheckboxProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    value(convertRawProp(context, rawProps, "value", sourceProps.value, {false})),
    disabled(convertRawProp(context, rawProps, "disabled", sourceProps.disabled, {false})),
    testID(convertRawProp(context, rawProps, "testID", sourceProps.testID, {})),
    lineWidth(convertRawProp(context, rawProps, "lineWidth", sourceProps.lineWidth, {0.0})),
    hideBox(convertRawProp(context, rawProps, "hideBox", sourceProps.hideBox, {false})),
    tintColor(convertRawProp(context, rawProps, "tintColor", sourceProps.tintColor, {})),
    onCheckColor(convertRawProp(context, rawProps, "onCheckColor", sourceProps.onCheckColor, {})),
    onFillColor(convertRawProp(context, rawProps, "onFillColor", sourceProps.onFillColor, {})),
    onTintColor(convertRawProp(context, rawProps, "onTintColor", sourceProps.onTintColor, {})),
    animationDuration(convertRawProp(context, rawProps, "animationDuration", sourceProps.animationDuration, {0.0}))
      {}

} // namespace react
} // namespace facebook
