
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <jsi/jsi.h>
#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/graphics/Color.h>

namespace facebook {
namespace react {

class JSI_EXPORT RNCCheckboxProps final : public ViewProps {
 public:
  RNCCheckboxProps() = default;
  RNCCheckboxProps(const PropsParserContext& context, const RNCCheckboxProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props
  bool value{false};
  bool disabled{false};
  SharedColor onCheckColor{};
  SharedColor tintColor{};
};

} // namespace react
} // namespace facebook
