
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>
#include "Props.h"

namespace facebook {
namespace react {

    RNCCheckboxProps::RNCCheckboxProps(const PropsParserContext &context, const RNCCheckboxProps &sourceProps,
                                       const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),
            value(convertRawProp(context, rawProps, "value", sourceProps.value, {false})),
            disabled(convertRawProp(context, rawProps, "disabled", sourceProps.disabled, {false})),
            onCheckColor(convertRawProp(context, rawProps, "onCheckColor", sourceProps.onCheckColor, {})),
            markSize(convertRawProp(context, rawProps, "markSize", sourceProps.markSize, {-1.0})),
            strokeWidth(convertRawProp(context, rawProps, "strokeWidth", sourceProps.strokeWidth, {-1.0})),
            strokeColor(convertRawProp(context, rawProps, "strokeColor", sourceProps.strokeColor, {})),
            tintColor(convertRawProp(context, rawProps, "tintColor", sourceProps.tintColor, {}))
    {}

} // namespace react
} // namespace facebook
